defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  host: linus.mongohq.com
  port: 10056
  database: kiln_development
  username: rails_user
  password: jfro9ae3)FAE0qx

test:
  <<: *defaults
  database: kiln_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: linus.mongohq.com
  port: 10056
  database: kiln_production
  username: rails_user
  password: jfro9ae3)FAE0qx
